semantic_parser:
  model: "azure/gpt-4o"
  temperature: 0.0
  max_tokens: 512
  top_p: 1.0
  frequency_penalty: 0.0
  presence_penalty: 0.0


response_generator:
  model: "azure/gpt-4o"
  temperature: 0.0
  max_tokens: 512
  top_p: 1.0
  frequency_penalty: 0.0
  presence_penalty: 0.0
